<?php

namespace GameBundle\Repository;

/**
 * BuildingRequiredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingRequiredRepository extends \Doctrine\ORM\EntityRepository
{
}
