<?php
/**
 * This file is part of the World Of Shinobi (Minegame).
 *
 * Copyright (c) 2017. Vincent Glize <vincent.glize@live.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace GameBundle\Repository;

/**
 * BatimentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBuildingProducts() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT bt FROM GameBundle:BuildingType bt
                WHERE bt.ressource is not null
                     '
            )
            ->getResult();
    }

    public function getBuildings() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT bt FROM GameBundle:BuildingType bt
                 WHERE bt.ressource is null
                 ORDER BY bt.id'
            )
            ->getResult();
    }

    public function getBuilding($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT bt, b, r, re, i FROM GameBundle:BuildingType bt
                 JOIN bt.buildings b
                 LEFT JOIN b.required r
                 LEFT JOIN bt.image i
                 LEFT JOIN b.ressources re
                 WHERE bt.id = :id
                 ORDER BY b.lvl DESC, re.id'
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }
}
