<?php

namespace GameBundle\Repository;

/**
 * BuildingRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingRessourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll() {
        return $this->getEntityManager()
                ->createQuery(
                    'SELECT br, r, b FROM GameBundle:BuildingRessource br
                     JOIN br.ressource r
                     JOIN br.building b ORDER BY br.id'
                )
                ->getResult();
    }

    public function getAllById($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT br, r, b FROM GameBundle:BuildingRessource br
                 JOIN br.ressource r
                 JOIN br.building b
                 WHERE b.id = :id ORDER BY br.id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
