<?php

namespace GameBundle\Repository;

/**
 * BatimentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBuildingProducts() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT bt FROM GameBundle:BuildingType bt
                WHERE bt.ressource is not null
                     '
            )
            ->getResult();
    }

    public function getBuildings() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT bt FROM GameBundle:BuildingType bt
                 WHERE bt.ressource is null
                 ORDER BY bt.id'
            )
            ->getResult();
    }

    public function getBuilding($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT bt, b, r, re FROM GameBundle:BuildingType bt
                 JOIN bt.buildings b
                 LEFT JOIN b.required r
                 JOIN b.ressources re
                 WHERE bt.id = :id
                 ORDER BY b.lvl DESC, re.id'
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }
}
