<?php

namespace GameBundle\Repository;

/**
 * ClanAllyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanAllyRepository extends \Doctrine\ORM\EntityRepository
{
}
