<?php
/**
 * This file is part of the World Of Shinobi (Minegame).
 *
 * Copyright (c) 2017. Vincent Glize <vincent.glize@live.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace GameBundle\Repository;

/**
 * ClanUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUser($id) {
        return $this->getEntityManager()
            ->createQuery(
            'SELECT PARTIAL cu.{id, user, rank, clan}, PARTIAL u.{id, username} FROM GameBundle:ClanUser cu
             JOIN cu.user u
             WHERE u.id = :id
            ')
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }
}
