<?php

namespace GameBundle\Repository;

/**
 * ClanDiplomatyCandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanDiplomatyCandidatureRepository extends \Doctrine\ORM\EntityRepository
{
}
