<?php

namespace GameBundle\Repository;

/**
 * ClanDiplomatyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanDiplomatyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlly($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT PARTIAL c.{id}, PARTIAL d.{id, name, point, xp} FROM GameBundle:Clan c
                 JOIN c.diplomaty d
                 WHERE c.id = :id AND d.id = 1'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
