<?php

namespace GameBundle\Repository;

/**
 * ClanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT PARTIAL c.{id, name, point, xp} FROM GameBundle:Clan c
                 ORDER BY c.point')
            ->getResult();
    }

    public function getName($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT PARTIAL c.{id, name} FROM GameBundle:Clan c
                 WHERE c.id = :id'
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

    public function getClan($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c, PARTIAL ally.{id, name}, PARTIAL users.{id, user, rank}, PARTIAL user.{id, username},
                 PARTIAL rank.{id, name}, PARTIAL candidatures.{id, texte, user}, PARTIAL candidatureUser.{id, username},
                 PARTIAL candidatureAlly.{id, texte, clanSource}
                 FROM GameBundle:Clan c
                 LEFT JOIN c.ally ally
                 JOIN c.users users
                 JOIN users.user user
                 JOIN users.rank rank
                 LEFT JOIN c.candidatures candidatures
                 LEFT JOIN candidatures.user candidatureUser
                 LEFT JOIN c.candidatureAlly candidatureAlly
                 WHERE c.id = :id
                 '
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

    public function getClanInfoForUser($id, $user) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT PARTIAL c.{id, name, texte, point, xp}, u, PARTIAL us.{id, username}, PARTIAL ca.{id, texte}  FROM GameBundle:Clan c
                 JOIN c.users u
                 JOIN u.user us
                 LEFT JOIN c.candidatures ca WITH ca.user = :user
                 WHERE c.id = :id
                 '
            )
            ->setParameter('id', $id)
            ->setParameter('user', $user)
            ->getOneOrNullResult();
    }

    public function getAlly($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT PARTIAL c.{id}, PARTIAL a.{id, name, point, xp} FROM GameBundle:Clan c
                 JOIN c.ally a
                 WHERE c.id = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }

}
