<?php

namespace GameBundle\Repository;

/**
 * ClanUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanUserRepository extends \Doctrine\ORM\EntityRepository
{
}
