<?php
/**
 * This file is part of the World Of Shinobi (Minegame).
 *
 * Copyright (c) 2017. Vincent Glize <vincent.glize@live.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace GameBundle\Repository;

/**
 * ClanDiplomatyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanDiplomatyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAlly($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT PARTIAL c.{id}, PARTIAL d.{id, name, point, xp} FROM GameBundle:Clan c
                 JOIN c.diplomaty d
                 WHERE c.id = :id AND d.id = 1'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
