<?php

namespace GameBundle\Repository;

/**
 * ClanCandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanCandidatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function acccept($id) {
        return $this->getEntityManager()
            ->createQuery(
                'DELETE FROM GameBundle:ClanCandidature cc
                 WHERE cc.user = :id'
            )
            ->setParameter('id', $id)
            ->execute();
    }
}
