<?php

namespace GameBundle\Repository;

/**
 * ClanRankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanRankRepository extends \Doctrine\ORM\EntityRepository
{
}
