<?php
/**
 * This file is part of the World Of Shinobi (Minegame).
 *
 * Copyright (c) 2017. Vincent Glize <vincent.glize@live.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace GameBundle\Repository;

/**
 * ClanCandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanCandidatureRepository extends \Doctrine\ORM\EntityRepository
{
    public function acccept($id) {
        return $this->getEntityManager()
            ->createQuery(
                'DELETE FROM GameBundle:ClanCandidature cc
                 WHERE cc.user = :id'
            )
            ->setParameter('id', $id)
            ->execute();
    }
}
