<?php

namespace GameBundle\Repository;

/**
 * ClanAllyCandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanAllyCandidatureRepository extends \Doctrine\ORM\EntityRepository
{
}
