<?php

namespace GameBundle\Repository;

/**
 * DiplomatyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomatyRepository extends \Doctrine\ORM\EntityRepository
{
}
