<?php

namespace GameBundle\Repository;

/**
 * InfantryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfantryRepository extends \Doctrine\ORM\EntityRepository
{
}
