<?php

namespace GameBundle\Repository;

/**
 * InfantryTownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfantryTownRepository extends \Doctrine\ORM\EntityRepository
{
    public function addInfantry($infantry, $toCreate, $town) {
        return $this->getEntityManager()
            ->createQuery(
                'UPDATE GameBundle:InfantryTown i SET i.nb = i.nb + :nombre WHERE i.town = :town AND i.infantry = :infantry'
            )
            ->setParameters(array('nombre' => $toCreate, 'town' => $town, 'infantry'=>$infantry))
            ->execute();
    }

    public function nb($id, $town)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT PARTIAL ti.{id, nb} FROM GameBundle:InfantryTown ti
            WHERE ti.town = :town AND ti.infantry = :id')
            ->setParameters(array('town' => $town, 'id' => $id))
            ->getOneOrNullResult();
    }
}
