<?php

namespace GameBundle\Repository;

/**
 * InfantryRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfantryRessourceRepository extends \Doctrine\ORM\EntityRepository
{
}
