<?php

namespace GameBundle\Repository;

/**
 * InfantryBuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfantryBuildRepository extends \Doctrine\ORM\EntityRepository
{
}
