<?php

namespace GameBundle\Repository;

/**
 * InfantryTownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfantryTownRepository extends \Doctrine\ORM\EntityRepository
{
}
