<?php

namespace GameBundle\Repository;

/**
 * InfantryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfantryRepository extends \Doctrine\ORM\EntityRepository
{
    public function ifInBuilding($id) {
        return $this->getEntityManager()
            ->createQuery('SELECT PARTIAL i.{id, name} FROM GameBundle:Infantry i
                          WHERE i.buildingType = :id')
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }
}
