<?php
/**
 * This file is part of the World Of Shinobi (Minegame).
 *
 * Copyright (c) 2017. Vincent Glize <vincent.glize@live.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace GameBundle\Repository;
use GameBundle\Entity\Map;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMapByPosition(Map $position) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM GameBundle:Map m
                 WHERE m.x BETWEEN :xMini AND :xMax
                 AND m.y BETWEEN :yMini AND :yMax'
            )
            ->setParameters(array('xMini' => $position->getX() - 10, 'xMax' => $position->getX() + 10,
                                  'yMini' => $position->getY() - 10, 'yMax' => $position->getY() + 10))
            ->getResult();
    }
}
