<?php

namespace GameBundle\Repository;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends \Doctrine\ORM\EntityRepository
{
}
