<?php

namespace GameBundle\Repository;

/**
 * RessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRessource($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT tr, r FROM GameBundle:TownRessource tr
                 JOIN tr.ressource r
                 WHERE tr.town = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
