<?php

namespace GameBundle\Repository;

/**
 * TownInfantryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownInfantryRepository extends \Doctrine\ORM\EntityRepository
{
}
