<?php

namespace GameBundle\Repository;

/**
 * TownRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownRessourceRepository extends \Doctrine\ORM\EntityRepository
{
}
