<?php

namespace GameBundle\Repository;

/**
 * TownInfantryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownInfantryRepository extends \Doctrine\ORM\EntityRepository
{
    public function nb($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(ti.id) as nb FROM GameBundle:TownInfantry ti
            WHERE ti.infantry = :id')
            ->setParameter('id', $id)
            ->getSingleScalarResult();
    }
}
