<?php

namespace GameBundle\Repository;

/**
 * TypeBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
