<?php
/**
 * This file is part of the World Of Shinobi (Minegame).
 *
 * Copyright (c) 2017. Vincent Glize <vincent.glize@live.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Minegame\SupportBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTickets($user) {
        return $this->getEntityManager()
            ->createQuery("
            SELECT PARTIAL t.{id, title, type}, PARTIAL tt.{id, title}, PARTIAL m.{id}, PARTIAL u.{id, username} FROM MinegameSupportBundle:Ticket t
            LEFT JOIN t.type tt
            LEFT JOIN t.messages m 
            LEFT JOIN m.user u
            WHERE t.user = :user
            ")
            ->setParameter('user', $user)
            ->getResult();
    }
}
