<?php

namespace Minegame\SupportBundle\Repository;

/**
 * TicketTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
